version: "3"

services:
  fe:
    image: halverneus/static-file-server:latest
    restart: always
    volumes:
      - $PWD/dist:/content
    environment:
      - FOLDER=/content
    labels:
      - traefik.http.routers.fe.rule=Host(`fezhix${HOST_DOMAIN}`)
      - traefik.http.routers.fe.entrypoints=websecure
      - traefik.http.routers.fe.tls=true
      - traefik.http.routers.fe.tls.certresolver=leresolver
      - traefik.http.services=fe
      - traefik.http.services.fe.loadbalancer.server.port=8080
  zhix:
    image: zhix:dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD/database.sqlite3:/root/database.sqlite3
    networks:
      - default
    labels:
      - traefik.http.routers.zhix.rule=Host(`zhix${HOST_DOMAIN}`)
      - traefik.http.routers.zhix.entrypoints=websecure
      - traefik.http.routers.zhix.tls=true
      - traefik.http.routers.zhix.tls.certresolver=leresolver
      - traefik.http.services=zhix
      - traefik.http.services.zhix.loadbalancer.server.port=8000
networks:
  default:
    external:
      name: ${DOCKER_NETWORK:-webproxy}
